assignment2/Controllers/PatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FHIR_FIT3077.IRepositories;
using FHIR_FIT3077.Observer;
using FHIR_FIT3077.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FHIR_FIT3077.Controllers
{
    public class PatientController : Controller
    {
        private readonly ICacheRepository _cache;
        public PatientController(ICacheRepository distributedCache)
        {
            _cache = distributedCache;
        }
        public IActionResult PatientDisplay(string id)
        {
            var pracId = TempData["PracId"];
            var monitorKey = "Monitor" + pracId;
            var monitoredList = _cache.GetObject<List<MonitorModel>>(monitorKey);
            var patientDetailModel = new PatientDetailsViewModel();
            for (int i = 0; i < monitoredList.Count; i++)
            {
                if(monitoredList[i].Id == id)
                {
                    patientDetailModel.Id = monitoredList[i].Id;
                    patientDetailModel.Name = monitoredList[i].Name;
                    patientDetailModel.Birthdate = monitoredList[i].Birthdate;
                    patientDetailModel.Gender = monitoredList[i].Gender;
                    patientDetailModel.Address = monitoredList[i].Address;
                    patientDetailModel.City = monitoredList[i].City;
                    patientDetailModel.State = monitoredList[i].State;
                    patientDetailModel.Country = monitoredList[i].Country;
                }
            }
            return View(patientDetailModel);
        }
    }
}

assignment2/Controllers/PractitionerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FHIR_FIT3077.IRepositories;
using FHIR_FIT3077.IRepository;
using FHIR_FIT3077.Models;
using FHIR_FIT3077.Observer;
using FHIR_FIT3077.Repository;
using FHIR_FIT3077.ViewModel;
using Hl7.Fhir.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;

namespace FHIR_FIT3077.Controllers
{
    public class PractitionerController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        private readonly IPractitionerRepository _practitioner;
        private readonly ICacheRepository _cache;

        public PractitionerController(IPractitionerRepository practitioner, ICacheRepository distributedCache)
        {
            _practitioner = practitioner;
            _cache = distributedCache;
        }

        [HttpPost]
        [ActionName("SubmitId")]
        public IActionResult SubmitId(PractitionerModel model)
        {
            if (ModelState.IsValid)
            {
                _cache.Remove("Patient" + model.Id);
                _cache.Remove("Monitor" + model.Id);
                return RedirectToAction("LoadPatient", new {id = model.Id});
            }

            return Index();
        }


        //This method load all unique patients from the server and store the list in cache
        public IActionResult LoadPatient(string id)
        {
            string cacheKey = "Patients" + id;
            var patientViewModel = new PatientViewModel();
            if (_cache.ExistObject<Dictionary<string, PatientModel>>(cacheKey) == true)
            {
                Console.WriteLine("exist cache");
                var patientList = _cache.GetObject<Dictionary<string, PatientModel>>(cacheKey);
                patientViewModel.PatientList = patientList;
                TempData["PracId"] = id;
                ViewData["PractitionerId"] = id;
                return View(patientViewModel);
            }
            else
            {
                Console.WriteLine("create new cache");
                patientViewModel.PatientList = _practitioner.GetTotalPatients(id);
                _cache.SetObject(cacheKey, patientViewModel.PatientList);
                TempData["PracId"] = id;
                ViewData["PractitionerId"] = id;
                return View(patientViewModel);
            }
        }

        public IActionResult Update(string pracId)
        {
            string cacheMonitorKey = "Monitor" + pracId;
            string cachePatientKey = "Patients" + pracId;
            var monitorList = _cache.GetObject<List<MonitorModel>>(cacheMonitorKey);
            var patientList = _cache.GetObject<Dictionary<string, PatientModel>>(cachePatientKey);

            foreach (var pat in patientList)
            {
                pat.Value.Records = _practitioner.GetLatestRecords(pat.Value.Id);
            }
            _cache.SetObject(cachePatientKey, patientList);

            if (monitorList != null)
            {
                foreach (var monitor in monitorList)
                {
                    monitor.Update(patientList[monitor.Id]);
                }
                _cache.SetObject(cacheMonitorKey, monitorList);
                return RedirectToAction("UpdateMonitorView", "Monitor", new { pracId = pracId });
            }
            else
            {
                return new EmptyResult();
            }
            
           
        }
        
    }
}

assignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FHIR_FIT3077</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Practitioner" asp-action="Index">FHIR_FIT3077</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Practitioner" asp-action="Index">Practitioner</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FHIR_FIT3077 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

assignment2/Views/Shared/_MonitorSection.cshtml
@model FHIR_FIT3077.ViewModel.PatientViewModel;


<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Total Cholesterol</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.MonitorList.Count > 0)
        {
            @foreach (var item in Model.MonitorList)
            {
                bool renderedFlag = false;
                @foreach (var cholVal in (List<double>)ViewData["max"])
                {
                    
                    var value = Convert.ToDouble(item.Records[0].Value);
                    if (value == cholVal && Model.MonitorList.Count > 1)
                    {
                        <tr>
                            <td onclick="myClick(@item.Id)"><span style="color:red">@item.Name</span></td>
                            <td onclick="myClick(@item.Id)"><span style="color:red">@item.Records[0].Value</span></td>
                            <td onclick="myClick(@item.Id)"><span style="color:red">@item.Records[0].Date</span></td>
                        </tr>
                        renderedFlag = true;
                    }
                }
                if(!renderedFlag)
                {
                    <tr>
                        <td onclick="myClick(@item.Id)">@item.Name</td>
                        <td onclick="myClick(@item.Id)">@item.Records[0].Value</td>
                        <td onclick="myClick(@item.Id)">@item.Records[0].Date</td>
                    </tr>
                }


            }

        }
    </tbody>
</table>

<script>
    function myClick(id) {
        var url = '@Url.Action("PatientDisplay", "Patient", new { id = "__id__" })';
        window.location.href = url.replace('__id__', id);
    }
</script>